const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.TileMovement,
		C3.Plugins.shadowlight,
		C3.Behaviors.Orbit,
		C3.Behaviors.Tween,
		C3.Plugins.SVGPicture,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Button,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{Sine: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{TileMovement: 0},
	{Sine2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{ShadowLight: 0},
	{Orbit: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Tween: 0},
	{Sprite9: 0},
	{SVGPicture: 0},
	{c2: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Button: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Button2: 0},
	{Button3: 0},
	{Button4: 0},
	{TiledBackground2: 0},
	{ScrollTo: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Solid: 0},
	{TiledBackground6: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{TiledBackground9: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{diamond: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	SVGPicture: class extends self.ISVGPictureInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Button2: class extends self.IButtonInstance {},
	Button3: class extends self.IButtonInstance {},
	Button4: class extends self.IButtonInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {}
}